---
suppress-bibliography: true
reference-location: margin
citation-location: margin
---

# Initial thoughts on Teaching and Learning

### Definition or description of teaching 

Teaching is the dissemination of knowledge that can be applied and/or executed in both specific and other relevant contexts or situations for the purpose of solving problems, generating thoughtful discourse, or sparking innovation. Effective teaching is a display of depth of knowledge in a subject matter that is articulated in such a way that the gain of knowledge is sought after as a desirable treasure-quest instead of a means to the end of passing a course. As such, it depends heavily on the instructor’s ability to effectively communicate ideas to not only spark interest in the listener, but to instill creative curiosity beyond the duration of the class. I experienced such teaching in an Introduction to Sociology class in college. I recall walking into the class thinking of it as just another general education requirement that I needed to secure my graduation the following spring. However, from the very first class, the instructor drew my attention to matters I had become either disillusioned or indifferent towards including race theory, the glass ceiling theory, gender (in)equality and even the American constitution! He started the class, not by reading out the syllabus as was often the norm, but by sitting on the side of his desk and asking questions I had never even thought about (and there was no “right answer”!). This completely floored me and may have been the real beginning of my journey as a critical thinker. Through this course, I became more empathetic and open to diverse perspectives. More importantly, however, the study of sociology and social commentary has remained an active area of “pass-time research” that I engage in to date. An even greater indication of this effective teaching has been my conscious pursuit of sociology-based knowledge and its application in my interactions with colleagues, friends, and even strangers. 

### Definition or description of learning 

Learning is the process of acquiring knowledge, applying it, and being transformed by it. In my eyes, it often looks like Antoine de Saint-Exupéry’s Little Prince: a youthful fascination of the world and pursuit of greater understanding of matters within and beyond our conscious perception. As a person who loves learning (my definition of it), I have realized that it is quite different from mindless absorption of facts and theories. I struggle to dispel the apathy and bland grayness within me that often arises when “learning” is a means to get a certain grade in a class. I have, instead, grown to appreciate learning as a bite into some Willy Wonka-style treat: a process of tasty, spontaneous, sometimes ordered, delightful surprises. Body responses are quite telling of exciting and thrilling experiences. In my case, I often feel the giddy excitement of learning when I break a sweat as my heart races: something akin to first-date butterflies. Besides this, I know when learning has occurred when my initial thoughts on a matter have been transformed. As many other humans on this planet, I have my biased, sometimes misguided opinions on matters that I can defend with such passion and commitment. I know I have learned when such set-in-stone-perspectives have collided with new knowledge and either broken or have been strengthened as a result. Referring to my initial contact with Sociology (above), I knew I had learned when nearly all my biases that had been a result of my upbringing or internalization of falsehoods, were debunked. And it didn’t stop there. I have been undergoing continual transformation with the information I’ve acquired through my study in sociology that allow me to bring unseen sides of a story to conversation. Learning is not only a transformation of oneself, but a transformation of others through conversation. I wonder how the world would look like if effective learning really was ruling the day.

### Relationship between teaching and learning

Teaching and learning are like the semi-circles that complete a circle: the complete circle cannot be formed without the other. The most effective teachers have also been the most avid learners. They pour out from their ever-replenishing source of knowledge, often after they have immersed themselves into that experience of learning. Such educators are also well-known for their ability to learn from everyone, not just people at their level of education or renown. Learners, by absorbing this information, applying, and being transformed by it, engage in discourse and, often unintentionally, impart knowledge themselves, consequently stepping into the teaching role (albeit momentarily). In this process, a special kind of humility and bravery is required for both effective learning and teaching. Both paths often hit the wall of the “unknown” and require a sure meekness to press on without becoming disillusioned by the possibility of never really “arriving” at the predetermined destination. Isn’t the destination always changing anyway? 

### Influence of the learning environment on teaching and learning

An environment that fosters learning really breaks down the walls between students and instructors. These walls include: i) adherence to titles that often make the instructor seem out of reach, ii) the learners’ fear in challenging an instructor’s views, iii) the struggle for professors to initiate innovative and educative discussion in the classroom, among others. Reflecting on my past experiences, I recall the fear I had to even challenge unfair practices that were propagated by instructors in my high school years. We were at the mercy of each instructor’s expectations which were often too high and difficult to reach given the available hours in a day. Learning became synonymous with disappointment and failure cause that’s all it was ever made to feel like. The wonder of it all faded and fear took its place. There was an obsession with memorizing answers no matter how absurd they sounded with no room for a different perspective. My time at VAI has been a stark difference, with instructors and students taking more of a collegial role with open discussion, heated (but fun and respectful) disagreements, and a renewed excitement to learn from both sides. While it can be argued that these differences are due to the differences in level of education, I still believe that the model of collaborative learning and teaching can be applied to all levels of education, with the only difference being the intensity and measure of guidance from the instructor. 

### Two teaching pedagogies/strategies/methods that I'd like to use in a future teaching role

**Recall, Summarize, Question, Connect, and Comment.**
</br>
I am particularly fond of this method because it is centered on drawing and applying previous knowledge to solve current problems in varying contexts. During my time as a student, one question I often heard my peers asking (and me along with them) was, “When am I ever going to use this information? How would this even help me in future classes/my career?”. While it is impossible to predict the future, this learning strategy is a timeless tool. It empowers students to get to a solution regardless of their expertise. It also has the silent beauty of allowing students to make connections that transcend the walls of a classroom. In a subtle but powerful way, the mind begins to transform.

**Concept maps.**
</br>
I am quite enthused to incorporate concept maps into my lessons. While I have little practice making or using them, I have seen their utility in classes I have attended. Often, in scientific courses, the information passed on by professors can often seem overwhelming and disconnected. While I am all for the adventure of moving forward blindly, this, prolonged often leads to feelings of inadequacy and unpreparedness. I often find myself convincing myself that I just don’t know anything while, the more accurate deduction is that I just haven’t been shown how everything is connected. Making connections is much more efficient in learning than just absorbing information. That’s why I think that this would be a very important strategy to include. For example, I think that students would understand the point of learning a certain topic when time is allocated to filling in a new box after every key concept learned and showing how that relates to the previous concept and/or the main objective of a class.

### Two ways I'd ensure all students have equitable learning opportunities and feel welcomed/valued in the classroom

**Making uncertainty safe. Drawing from Chapter 6 of [How Learning Works](chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/https://firstliteracy.org/wp-content/uploads/2015/07/How-Learning-Works.pdf).**
</br>
There’s something to be said about allowing learning to be a path forged by overcoming mistakes and pitfalls instead of one with the unspoken and unrealistic expectation of perfection. My past educational experiences have been riddled with the latter, and this has often led me to shy away from asking questions for fear of not having known. That’s the point of learning! We don’t know, so we learn to know more. Then we rinse and repeat. I want to ensure that my students are aware of this from the first day. I think this will allow them to step out, boldly, as they pursue the knowledge the course has for them. We all need more adventurers in our classrooms to propel change among their peers, within us as instructors, and in the world.



