---
suppress-bibliography: true
reference-location: margin
citation-location: margin
---

# Statement of Teaching and Learning

> **Note:** 
> Phrases/words in bold are based on principles from Engineering Learning

Learning beckoned me from a young age. My mother recalls my incessant pleas to be enrolled in the local kindergarten at the age of one. Although at that time I lacked the vocabulary to explain my longing for education, I now realize that I sought the adventure of transformation and immersion into a culturally diverse space. In each classroom, I was exposed to fellow learners and teachers who embodied the tribal diversity in my country (Kenya) through their attire, choice of food, and language. Despite these rosy beginnings, I swiftly realized the sinister side to our system of education: obsession with grades. From the first grade, we (students) would be lined up during the morning assembly and either shamed or rewarded for our grades on the previous exam. We were pitted against each other and taught to compete for the top score in each test to prove our academic worth. This shifted the focus from learning as a process of transformation and, instead, made it an anxiety-inducing experience. With teachers ridiculing us for asking questions or not always knowing the correct answer in tests, we began to fear unknowns and steer clear of curiosity. It wasn’t until I moved to the States for college, that my enthusiasm for learning was revived. My instructors encouraged my inquisitive nature, supplemented my curiosity with their engaging discourse, and constantly provided guidance in projects that were too foreign for me. With this stark contrast to what I considered the norm, I could finally feel myself transform. At last, I was learning.

> My primary goal as a teacher is to motivate students to boldly approach the unknown. I feared the unknown for two reasons: i) a hostile and exclusionary class environment and ii) lack of guidance on how to get to the known. In my classroom, I intend to provide an explicitly inclusive environment where each student can freely express themselves without fear of ridicule. Additionally, I will practice and refine teaching techniques that equip students with skills to maneuver unchartered topics/questions. By applying these skills in an inclusive class setting, I will provide assessments to students that challenge them to explore new ideas to problems and provide a written and oral defense of their solutions. In this way, students will be tasked to defend their propositions and be given opportunities to improve their ideas through peer and instructor feedback. Ultimately, through continuous practice and constructive feedback, students will begin to approach the unknown fearlessly.

The boundless and frightful land of unknowns varies among students. To give space for each student to explore such lands, it is imperative to create an environment that includes diverse perspectives that students can relate to. This explicitly inclusive environment is quite prominent in the arts and humanities but is nearly absent in scientific contexts. I especially noticed this in graduate school, where ethical debates often failed to account for social contexts that would afford an offense some lenience. I also realized that most scientific texts covered in class excluded contributions from minority populations and were largely focused on Western medicine. Because of this, I intend to provide my students with opportunities to learn from the socio-cultural contexts of biomedical discoveries and established theories. This would allow them to learn how the basic concepts of biology came to be. By setting these innovations in cultural contexts, students would learn of how biomedical practices have shifted through time, populations, and geographical locations. Besides this, I will include readings and assignments that feature peer-reviewed publications from minority scientists, and other culturally distinct approaches to learning biology. This would give minority students the rare chance to “see themselves” in positions of scientific leadership. I believe that exposing students to the scientific method from such different sources would challenge their existing biases in the acquisition and application of knowledge. Giving students the opportunity to immerse themselves in something starkly different from their norm would not only establish and reinforce their empathy for others but also allow them to experience the discomfort of unlearning. In this explicitly inclusive space, through the process of learning and unlearning, I, and my students would be familiarizing ourselves with the new fringes of our unique unknowns.

The most renowned inventors and thinkers were simply skilled at using somewhat unremarkable events to explore new ideas. For instance, the rather simple kite experiment that Benjamin Franklin used to show the electric capabilities of lightning have since revolutionized our world. I believe that, besides learning all the complex details and fundamentals of biology, students should be educated on how to **connect the dots in their knowledge reserves to make electric discoveries**. By the time students approach the end of their undergraduate education, they are expected to be hubs of intelligent ideas. I, however, felt ill-suited to apply all the knowledge I had gained since I had scarcely been pushed to connect concepts from different biology courses to address a yet-unsolved research question. As a teacher, my goal is to equip students with skills that enable them to make connections between the known and unknown to solve scientific problems. In practice, this would begin with a prompt for students to recall what they know about a topic, connect their knowledge to the “big unanswered question”, and think of ways to address this question. If students are learning about inherited dental diseases, I would ask the students to **recall** what they know about inheritance. What do they know about dental hygiene and does this have anything to do with dental diseases? Such prompts would push students to explore the limits of their knowledge and look for ways to push those limits. By providing a guide on how to understand something that was initially unknown, I would accouter students with a “compass” to navigate unchartered topics. This approach would require me, as the instructor, to lead students, step-by-step, through the first few class questions, to get them comfortable with the process. Then slowly, I would let each student chart their own path as I provide reassurance and correction along the way. In this way, students will get to exercise autonomy of thought within the reins of the course objectives. This may yet reveal the beginnings of great scientific thinkers.

Practice is a main part of how we gain mastery. To help my students achieve mastery in tackling any scientific problem, I will provide a few instances of **formative assessments** throughout the course. These assessments would be structured in a way that reinforces the concepts learned in class while pushing them to learn something new in preparation for the next session. For example, if a class session covers anodontia, a congenital dental disease, students will be tasked to identify the key genes that have been implicated in this disorder to recap the information gained in class. To push them to learn something new, I would ask students to provide a written summary of how the malfunction of these genes affects the normal biology in a tooth. What pathways are involved? Is this gene related to another disease that’s not related to teeth? Does this related disease share any similarities with anodontia? Through such assessments, students would not only practice the knowledge gained on a particular subject matter, but also relate that knowledge to other diseases or pathways. By connecting such disparate diseases, students would practice making connections between the known (material covered in class) and the unknown (a concept they would freely explore in the completion of their assignments). Besides instilling curiosity in students, such formative assessments would also prepare students for the **summative assessment** at the end of the course which would be a written paper on a disease of their choice, and an oral presentation on the same. With time, intense focus, and practice, my students will steadily be on the path to mastery.

My cross-continental learning experience continues to create wanderlust for the unknown in me. As a teacher, I hope to instill a similar sense of adventure in my students even in the face of challenging biological concepts. I aim to create an environment where each student feels included and equipped to handle the demands of my course, and others thereafter. Through this, I believe my students would appreciate the continuous and transformative process of learning. They would step through the door of something yet unexplored and leave having their perspectives changed. In the application of these remolded perspectives, they would acquire new skills, replace old beliefs, and make new connections to the world around them. 
 
