---
suppress-bibliography: true
reference-location: margin
citation-location: margin
---

# In-class teaching experience

Immanuel Kant, the renowned German philosopher in the age of Enlightenment once said 

> Experience without theory is blind, but theory without experience is mere intellectual play.

In the same vain, after much theory on pedagogical practice and reflection on my goals as a teacher, I sought to put my knowledge to practice by designing a lesson plan and executing it.

This was done in collaboration with the Biology Department at Aquinas College, Grand Rapids, MI. I was tasked with preparing for a Microbiology class on Unique Bacterial Phyla.

This classroom was flipped in that it was centered on students working in groups to answer questions on a handout I created before discussing some of the solutions as a class.

Below, I have provided the link to the Lesson Plan and the Handout (with the answer scheme) that each student received to work on during class

- [Lesson Plan](https://vanandelinstitute-my.sharepoint.com/:w:/g/personal/svetlana_djirackor_vai_org/EWwgP6ZwMu1AoYx4Uko9tv4BeBTqPnHjr6Nr8VO5EbABgw?e=xkA6Ay)

- [Unique Bacterial Phyla Handout](https://vanandelinstitute-my.sharepoint.com/:w:/g/personal/svetlana_djirackor_vai_org/EbNJ1DjIV-1Frkis50HHTwIBJ2gdTIG49pTer2u4m5qhUw?e=LmXWS1)